import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isRasterFile, sensitivePathMatches } from './lib/privacy.mjs';

const args = process.argv.slice(2);
const rootIndex = args.indexOf('--root');
const defaultSkillRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const skillRoot = rootIndex >= 0 ? path.resolve(args[rootIndex + 1] || '') : defaultSkillRoot;
const forbiddenDirectories = new Set(['preview', 'release', 'dist', 'node_modules']);
const ignoredDirectories = new Set(['.git']);
const piiTextExtensions = new Set(['.json', '.md', '.yaml', '.yml', '.txt', '.log', '.js', '.mjs']);
const reservedEmailDomains = new Set(['example.com', 'example.net', 'example.org', 'example.test']);
const publicMaintainerRasterAssets = new Map([
  ['assets/community/wechat-learning-group.jpg', '0d5afa9f4f6e0d25022ca828d339a1cb9fe58c734477c72a2eb00557bea2838e'],
  ['assets/community/xiaohongshu-wetianshuo.jpg', 'cc1300f7861201c8d37f540fc8e44cf78b9ad0cb7006584273746e3d88eac88b']
]);
const errors = [];
const files = [];
const seenPublicMaintainerAssets = new Set();
const stack = [skillRoot];

if (rootIndex >= 0 && !args[rootIndex + 1]) {
  console.error('- --root requires a directory.');
  process.exit(1);
}

function sourceCodeSensitivePathMatches(text) {
  return sensitivePathMatches(text).filter((match) => {
    if ([...match].every((character) => character === '\\')) return false;
    const decoded = match.replaceAll('\\\\', '\\');
    if (/^[A-Za-z]:\\Windows\\System32\\cmd\.exe$/i.test(decoded)) return false;
    if (match.startsWith('\\\\') && !match.startsWith('\\\\\\\\')) return false;
    if (/\\s|\\u[0-9a-f]{4}|\[\^|\.test\(|\]\/|\$&|roundedX/i.test(match)) return false;
    return true;
  });
}

function piiIssues(text, sourceCode = false) {
  const issues = [];
  const emails = text.match(/[A-Z0-9._%+-]+@([A-Z0-9.-]+\.[A-Z]{2,})/gi) || [];
  if (emails.some((email) => !reservedEmailDomains.has(email.split('@').at(-1).toLowerCase()))) {
    issues.push('email address');
  }
  if (/(?:姓名|真实姓名|联系人姓名|full\s+name|legal\s+name|contact\s+name)\s*[:：]\s*(?!<|\[|\{|example\b|test\b|placeholder\b|your\b)\S+/im.test(text)) {
    issues.push('personal name');
  }
  if (/(?:微信号?|wechat(?:\s+id)?|qq号?|账号|account(?:\s+(?:id|name))?|用户名|username)\s*[:：]\s*(?!<|\[|\{|example\b|test\b|placeholder\b|your\b|person-\d+\b)\S+/im.test(text)) {
    issues.push('account identifier');
  }
  if ((sourceCode ? sourceCodeSensitivePathMatches(text) : sensitivePathMatches(text)).length) issues.push('private path');
  return issues;
}

function sha256File(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

while (stack.length) {
  const current = stack.pop();
  for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
    const full = path.join(current, entry.name);
    const relative = path.relative(skillRoot, full);
    if (entry.isDirectory()) {
      if (ignoredDirectories.has(entry.name)) continue;
      const portableRelative = relative.split(path.sep).join('/');
      if (portableRelative === 'docs/superpowers') errors.push(`Private planning document directory must not be published inside the Skill: ${relative}`);
      else if (forbiddenDirectories.has(entry.name)) errors.push(`Generated/runtime directory must not be published inside the Skill: ${relative}`);
      else stack.push(full);
      continue;
    }
    if (!entry.isFile()) continue;
    files.push(relative);
    if (isRasterFile(full)) {
      const portableRelative = relative.split(path.sep).join('/');
      const expectedHash = publicMaintainerRasterAssets.get(portableRelative);
      if (!expectedHash) errors.push(`Raster image must be generated by the current user, not bundled in the Skill: ${relative}`);
      else if (sha256File(full) !== expectedHash) errors.push(`Public maintainer raster asset hash does not match the reviewed file: ${relative}`);
      else seenPublicMaintainerAssets.add(portableRelative);
    }
    if (path.extname(entry.name).toLowerCase() === '.svg' && /data:image\//i.test(fs.readFileSync(full, 'utf8'))) {
      errors.push(`SVG must not embed raster image data: ${relative}`);
    }
    if (fs.statSync(full).size > 1024 * 1024) errors.push(`Unexpected file larger than 1 MiB: ${relative}`);
    const extension = path.extname(entry.name).toLowerCase();
    if (piiTextExtensions.has(extension)) {
      for (const issue of piiIssues(fs.readFileSync(full, 'utf8'), extension === '.js' || extension === '.mjs')) {
        errors.push(`Text ${issue} must not be published in the Skill: ${relative}`);
      }
    }
  }
}

const readmePath = path.join(skillRoot, 'README.md');
const readmeText = fs.existsSync(readmePath) ? fs.readFileSync(readmePath, 'utf8') : '';
for (const relative of seenPublicMaintainerAssets) {
  if (!readmeText.includes(relative)) errors.push(`Public maintainer raster asset is not referenced by README.md: ${relative}`);
}
if (seenPublicMaintainerAssets.size > 0 && !/二维码及其中的作者头像由作者本人主动公开/.test(readmeText)) {
  errors.push('README.md must explicitly disclose that bundled maintainer contact QR assets were voluntarily made public by the maintainer.');
}

if (!files.includes(path.join('assets', 'electron-template', 'src', 'assets', 'sprites', 'placeholder.svg'))) {
  errors.push('The generic SVG placeholder is missing from the Electron template.');
}

if (errors.length) {
  console.error(errors.map((error) => `- ${error}`).join('\n'));
  process.exit(1);
}

console.log(`Release privacy audit passed: ${files.length} files; no private raster/person assets and ${seenPublicMaintainerAssets.size} reviewed public maintainer contact asset(s).`);
